export DOMAIN_NAME=live.videostream.site
export PROSODY_GLOBAL_CONFIG=/etc/prosody/prosody.cfg.lua
export PROSODY_CONFIG=/etc/prosody/conf.avail/"$DOMAIN_NAME".cfg.lua
export JICOFO_SIP_PROPS=/etc/jitsi/jicofo/sip-communicator.properties
export JITSI_MEET_CONFIG=/etc/jitsi/meet/"$DOMAIN_NAME"-config.js
export JITSI_MEET_INTERFACE_CONFIG=/usr/share/jitsi-meet/interface_config.js
export JITSI_USER=guest
export JITSI_PASSWORD=password123
export APP_NAME="Live Video"
export JIBRI_CONFIG=/etc/jitsi/jibri/config.json
export RECORDINGS_DIR=/recordings
export JIBRI_PASSWORD=ZHpUabnRR477
export RECORDER_PASSWORD=uGV46eVo0Qg3
